import type { Author, FeedPost } from "@/types/nectary";

const authors: Record<string, Author> = {
  mara: { name: "Mara Solano", handle: "marawrites", initials: "MS", tint: "cuento", level: 14 },
  iván: { name: "Iván Reyes", handle: "ivanverse", initials: "IR", tint: "poesia", level: 9 },
  noor: { name: "Noor Haddad", handle: "noor_ink", initials: "NH", tint: "novela", level: 21 },
  teo: { name: "Téo Marchetti", handle: "teodraft", initials: "TM", tint: "ensayo", level: 6 },
  lin: { name: "Lin Park", handle: "linpages", initials: "LP", tint: "primary", level: 17 },
  saga: { name: "Saga Lund", handle: "sagalund", initials: "SL", tint: "spark", level: 11 },
};

export const FEED_POSTS: FeedPost[] = [
  {
    id: "s1",
    type: "spark",
    category: "poesia",
    author: authors.iván,
    body: "A lighthouse that has forgotten the shape of the coast it was built to warn. It keeps turning anyway, out of habit, out of love.",
    createdAt: "2h",
    reactions: { likes: 42 },
    forks: 6,
  },
  {
    id: "w1",
    type: "wip",
    category: "novela",
    author: authors.noor,
    title: "The Cartographer's Daughter",
    summary:
      "A coming-of-age epic following a girl who inherits maps of places that no longer exist — and the debts that come with them.",
    status: "blocked",
    progress: 64,
    currentBlock: "Stuck on the second-act reveal — the betrayal feels unearned without more setup in Ch. 4.",
    wordCount: 58200,
    createdAt: "5h",
    reactions: { likes: 42 },
    forks: 23,
  },
  {
    id: "s2",
    type: "spark",
    category: "cuento",
    author: authors.mara,
    body: "What if the last bookstore in the city only sold books you'd already read — and charged you in the memories you'd lost of them?",
    createdAt: "1h",
    reactions: { likes: 42 },
    forks: 14,
  },
  {
    id: "s3",
    type: "spark",
    category: "ensayo",
    author: authors.teo,
    body: "We don't write to be understood. We write to find out whether we understood ourselves in the first place.",
    createdAt: "3h",
    reactions: { likes: 42 },
    forks: 31,
  },
  {
    id: "pm1",
    type: "postmortem",
    category: "novela",
    author: authors.lin,
    title: "Why I abandoned my 90k-word draft",
    body: "I confused momentum for direction. For eight months I wrote fast and never asked what the book was actually about. By the time I stopped, I had a thousand beautiful scenes and no spine.",
    lesson: "Outline the emotional question first. Prose can wait; intent cannot.",
    wordCount: 35,
    createdAt: "8h",
    reactions: { likes: 42 },
    forks: 12,
  },
  {
    id: "s4",
    type: "spark",
    category: "poesia",
    author: authors.saga,
    body: "Grief is just love with nowhere left to go, so it paces the hallway of the chest at 3am.",
    createdAt: "40m",
    reactions: { likes: 42 },
    forks: 9,
  },
  {
    id: "w2",
    type: "wip",
    category: "ensayo",
    author: authors.teo,
    title: "On the Quiet Violence of Deadlines",
    summary:
      "A long-form essay collection about creative pressure, productivity culture, and the ethics of the unfinished.",
    status: "in-progress",
    progress: 38,
    wordCount: 14300,
    createdAt: "12h",
    reactions: { likes: 42 },
    forks: 7,
  },
  {
    id: "s5",
    type: "spark",
    category: "cuento",
    author: authors.mara,
    body: "Two strangers keep meeting in revolving doors. Neither ever makes it inside.",
    createdAt: "6h",
    reactions: { likes: 42 },
    forks: 4,
  },
  {
    id: "w3",
    type: "wip",
    category: "cuento",
    author: authors.saga,
    title: "Salt & Static",
    summary: "A short story cycle set in a coastal town where the radio only plays the future.",
    status: "resolved",
    progress: 100,
    wordCount: 22100,
    createdAt: "1d",
    reactions: { likes: 42 },
    forks: 19,
  },
];
